//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.Game.Pipeline.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.Game.Pipeline.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .area asset identified by {0} consists of a single &apos;null&apos; literal token, which cannot be processed as an area. A JSON document conforming to the .area schema found at https://BadEcho.com/area.json must be provided..
        /// </summary>
        internal static string AreaIsNull {
            get {
                return ResourceManager.GetString("AreaIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property of the .area asset was provided as a &apos;null&apos; literal token, which is not permitted. Omit the property entirely if it is not needed..
        /// </summary>
        internal static string AreaPropertyIsNull {
            get {
                return ResourceManager.GetString("AreaPropertyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .atlas asset identified by {0} consists of a single &apos;null&apos; JSON token, which cannot be processed as a texture atlas. Ensure there were no errors when performing the export with TexturePacker..
        /// </summary>
        internal static string AtlasIsNull {
            get {
                return ResourceManager.GetString("AtlasIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atlas region identified by {0} is configured to use 9-slice scaling but has no slices across its bottom side..
        /// </summary>
        internal static string AtlasRegionNoBottomSlices {
            get {
                return ResourceManager.GetString("AtlasRegionNoBottomSlices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atlas region identified by {0} is configured to use 9-slice scaling but has no slices across its center..
        /// </summary>
        internal static string AtlasRegionNoCenterHorizontalSlices {
            get {
                return ResourceManager.GetString("AtlasRegionNoCenterHorizontalSlices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atlas region identified by {0} is configured to use 9-slice scaling but has no slices down its center..
        /// </summary>
        internal static string AtlasRegionNoCenterVerticalSlices {
            get {
                return ResourceManager.GetString("AtlasRegionNoCenterVerticalSlices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atlas region identified by {0} is configured to use 9-slice scaling but has no slices down its left side..
        /// </summary>
        internal static string AtlasRegionNoLeftSlices {
            get {
                return ResourceManager.GetString("AtlasRegionNoLeftSlices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atlas region identified by {0} is configured to use 9-slice scaling but has no slices down its right side..
        /// </summary>
        internal static string AtlasRegionNoRightSlices {
            get {
                return ResourceManager.GetString("AtlasRegionNoRightSlices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atlas region identified by {0} is configured to use 9-slice scaling but has no slices across its top side..
        /// </summary>
        internal static string AtlasRegionNoTopSlices {
            get {
                return ResourceManager.GetString("AtlasRegionNoTopSlices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Type: {0}, Width: {1}, Height: {2}.
        /// </summary>
        internal static string BoundedTextureCharacteristics {
            get {
                return ResourceManager.GetString("BoundedTextureCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bounded texture uses a shape of type &apos;{0}&apos; which is not yet supported..
        /// </summary>
        internal static string BoundedTextureUnsupportedShapeType {
            get {
                return ResourceManager.GetString("BoundedTextureUnsupportedShapeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All lines connecting two points on the edge of the circle through the center must have the same length; therefore, the circle must have the same width and height..
        /// </summary>
        internal static string CircleNeedsSameWidthHeight {
            get {
                return ResourceManager.GetString("CircleNeedsSameWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset &apos;{0}&apos; is already referenced by this content item with different build settings..
        /// </summary>
        internal static string ConflictingReferenceInContentItem {
            get {
                return ResourceManager.GetString("ConflictingReferenceInContentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency &apos;{0}&apos;: &apos;{1}&apos; is a directory instead of a file..
        /// </summary>
        internal static string DependencyFileIsADirectory {
            get {
                return ResourceManager.GetString("DependencyFileIsADirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No path for the dependency &apos;{0}&apos; was provided..
        /// </summary>
        internal static string DependencyPathIsEmpty {
            get {
                return ResourceManager.GetString("DependencyPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .sdfont asset identified by {0} consists of a single &apos;null&apos; literal token, which cannot be processed as a distance field font. A JSON document conforming to the .sdfont schema found at https://BadEcho.com/sdfont.json must be provided..
        /// </summary>
        internal static string DistanceFieldFontIsNull {
            get {
                return ResourceManager.GetString("DistanceFieldFontIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON layout file for the font consists of a single &apos;null&apos; literal, which cannot be processed as metadata for the distance field font. This is most likely due to an internal error during MSDF atlas generation..
        /// </summary>
        internal static string DistanceFieldFontJsonIsNull {
            get {
                return ResourceManager.GetString("DistanceFieldFontJsonIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font atlas generation did not output a JSON layout file..
        /// </summary>
        internal static string DistanceFieldFontNoJsonOutput {
            get {
                return ResourceManager.GetString("DistanceFieldFontNoJsonOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font atlas generation did not output an atlas texture file..
        /// </summary>
        internal static string DistanceFieldFontNoOutput {
            get {
                return ResourceManager.GetString("DistanceFieldFontNoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom property type &apos;{0}&apos; parser returned a null value despite a successful parse of the custom property &apos;{1}&apos; with value &apos;{2}&apos;..
        /// </summary>
        internal static string ExtensibleParsedNullPropertyValue {
            get {
                return ResourceManager.GetString("ExtensibleParsedNullPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom property &apos;{0}&apos; of type &apos;{1}&apos; with value &apos;{2}&apos; could not be parsed..
        /// </summary>
        internal static string ExtensibleUnparseablePropertyValue {
            get {
                return ResourceManager.GetString("ExtensibleUnparseablePropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset contains a custom property of type &apos;{0}&apos; which is not supported..
        /// </summary>
        internal static string ExtensibleUnsupportedType {
            get {
                return ResourceManager.GetString("ExtensibleUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image layer contains no image data..
        /// </summary>
        internal static string ImageLayerNoImage {
            get {
                return ResourceManager.GetString("ImageLayerNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing area: {0}.
        /// </summary>
        internal static string ImportingArea {
            get {
                return ResourceManager.GetString("ImportingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding dependency: {0}.
        /// </summary>
        internal static string ImportingDependency {
            get {
                return ResourceManager.GetString("ImportingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing distance field font: {0}.
        /// </summary>
        internal static string ImportingDistanceFieldFont {
            get {
                return ResourceManager.GetString("ImportingDistanceFieldFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished importing {0}.
        /// </summary>
        internal static string ImportingFinished {
            get {
                return ResourceManager.GetString("ImportingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing sprite sheet: {0}.
        /// </summary>
        internal static string ImportingSpriteSheet {
            get {
                return ResourceManager.GetString("ImportingSpriteSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing texture atlas: {0}.
        /// </summary>
        internal static string ImportingTextureAtlas {
            get {
                return ResourceManager.GetString("ImportingTextureAtlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing tile map: {0}.
        /// </summary>
        internal static string ImportingTileMap {
            get {
                return ResourceManager.GetString("ImportingTileMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing tile set: {0}.
        /// </summary>
        internal static string ImportingTileSet {
            get {
                return ResourceManager.GetString("ImportingTileSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No importer for file extension &apos;{0}&apos; found..
        /// </summary>
        internal static string NoImporterForFileExtension {
            get {
                return ResourceManager.GetString("NoImporterForFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference to the asset &apos;{0}&apos; was found on this content item..
        /// </summary>
        internal static string NoReferenceInContentItem {
            get {
                return ResourceManager.GetString("NoReferenceInContentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map object &apos;{0}&apos; (id {1}) uses an unsupported shape and will be ignored..
        /// </summary>
        internal static string ObjectUnsupportedShape {
            get {
                return ResourceManager.GetString("ObjectUnsupportedShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing area: {0}.
        /// </summary>
        internal static string ProcessingArea {
            get {
                return ResourceManager.GetString("ProcessingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing bounded texture: {0}.
        /// </summary>
        internal static string ProcessingBoundedTexture {
            get {
                return ResourceManager.GetString("ProcessingBoundedTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing distance field font: {0}.
        /// </summary>
        internal static string ProcessingDistanceFieldFont {
            get {
                return ResourceManager.GetString("ProcessingDistanceFieldFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing {0}.
        /// </summary>
        internal static string ProcessingFinished {
            get {
                return ResourceManager.GetString("ProcessingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing sprite sheet: {0}.
        /// </summary>
        internal static string ProcessingSpriteSheet {
            get {
                return ResourceManager.GetString("ProcessingSpriteSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing texture atlas: {0}.
        /// </summary>
        internal static string ProcessingTextureAtlas {
            get {
                return ResourceManager.GetString("ProcessingTextureAtlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing tile map: {0}.
        /// </summary>
        internal static string ProcessingTileMap {
            get {
                return ResourceManager.GetString("ProcessingTileMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing tile set: {0}.
        /// </summary>
        internal static string ProcessingTileSet {
            get {
                return ResourceManager.GetString("ProcessingTileSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite sheet must be configured to have one or more columns in order to be considered valid..
        /// </summary>
        internal static string SheetHasNoColumns {
            get {
                return ResourceManager.GetString("SheetHasNoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite sheet must be configured to have one or more rows in order to be considered valid..
        /// </summary>
        internal static string SheetHasNoRows {
            get {
                return ResourceManager.GetString("SheetHasNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial frame index exceeds the number of frames in the sprite sheet..
        /// </summary>
        internal static string SheetInitialFrameOutOfRange {
            get {
                return ResourceManager.GetString("SheetInitialFrameOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid animation sequence in the sprite sheet; starting index must be less than or equal to ending index..
        /// </summary>
        internal static string SheetInvalidAnimationSequence {
            get {
                return ResourceManager.GetString("SheetInvalidAnimationSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .spritesheet asset identified by {0} consists of a single &apos;null&apos; literal token, which cannot be processed as sprite sheet. A JSON document conforming to the .spritesheet schema found at https://BadEcho.com/spritesheet.json must be provided..
        /// </summary>
        internal static string SheetIsNull {
            get {
                return ResourceManager.GetString("SheetIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All animations in the sprite sheet must have unique names..
        /// </summary>
        internal static string SheetNonUniqueAnimationNames {
            get {
                return ResourceManager.GetString("SheetNonUniqueAnimationNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of animation frames exceeds the maximum allowed by the sprite sheet&apos;s configured dimensions..
        /// </summary>
        internal static string SheetTooManyFrames {
            get {
                return ResourceManager.GetString("SheetTooManyFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; tile layer encoding is not supported..
        /// </summary>
        internal static string TileLayerEncodingUnsupported {
            get {
                return ResourceManager.GetString("TileLayerEncodingUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile layer contains no tile data..
        /// </summary>
        internal static string TileLayerNoData {
            get {
                return ResourceManager.GetString("TileLayerNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map does not specify its orientation. This is a required setting..
        /// </summary>
        internal static string TileMapMissingOrientation {
            get {
                return ResourceManager.GetString("TileMapMissingOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map does not specify the render order of its tiles. This is a required setting..
        /// </summary>
        internal static string TileMapMissingRenderOrder {
            get {
                return ResourceManager.GetString("TileMapMissingRenderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map contains a layer of type &apos;{0}&apos; which is not supported..
        /// </summary>
        internal static string TileMapUnsupportedLayerType {
            get {
                return ResourceManager.GetString("TileMapUnsupportedLayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map uses an unsupported &apos;{0}&apos; map orientation..
        /// </summary>
        internal static string TileMapUnsupportedOrientation {
            get {
                return ResourceManager.GetString("TileMapUnsupportedOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map uses an unsupported &apos;{0}&apos; tile rendering order..
        /// </summary>
        internal static string TileMapUnsupportedRenderOrder {
            get {
                return ResourceManager.GetString("TileMapUnsupportedRenderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map object &apos;{0}&apos; (id {1}) is classed as a transition point but has no &apos;{2}&apos; custom property..
        /// </summary>
        internal static string TransitionObjectMissingProperty {
            get {
                return ResourceManager.GetString("TransitionObjectMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map object &apos;{0}&apos; (id {1}) declared the custom property &apos;{2}&apos; using the wrong type (expected: &apos;{3}&apos;, actual: &apos;{4}&apos;)..
        /// </summary>
        internal static string TransitionObjectPropertyWrongType {
            get {
                return ResourceManager.GetString("TransitionObjectPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map object &apos;{0}&apos; (id {1}) is a transition point rotated by {2} degrees; only axis-aligned regions are supported..
        /// </summary>
        internal static string TransitionObjectRotated {
            get {
                return ResourceManager.GetString("TransitionObjectRotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map object &apos;{0}&apos; (id {1}) is a zero-sized transition point region..
        /// </summary>
        internal static string TransitionObjectZeroSize {
            get {
                return ResourceManager.GetString("TransitionObjectZeroSize", resourceCulture);
            }
        }
    }
}
